### ISSUE TITLE
stop() can throw undefined errors

### ISSUE THREAD

**Issue by mattbishop** [kibertoad/toad-scheduler#199]
I am closing a toad scheduler instance using a shutdown hook and I often see this error when the hook calls stop():

```
Cannot read properties of undefined (reading 'engines')
    err: {
      "type": "TypeError",
      "message": "Cannot read properties of undefined (reading 'engines')",
      "stack":
          TypeError: Cannot read properties of undefined (reading 'engines')
              at stop (/Users/matt/Projects/evently/evently-monorepo/node_modules/toad-scheduler/dist/lib/toadScheduler.js:40:49)
              at fn (file:///Users/matt/Projects/evently/evently-monorepo/admin-api/src/shutdown.ts:8:36)
              at async run (/Users/matt/Projects/evently/evently-monorepo/node_modules/close-with-grace/index.js:92:19)
    }
```

Not sure what is happening exactly, but a bit more defensiveness with checking for `engines !== undefined` would help the close() function.

**Comment by kibertoad** [comment]
thank you for the report! will take a look
