### ISSUE TITLE
使用村容

### ISSUE THREAD

**Issue by LianXiaoxiang** [kibertoad/toad-scheduler#220]
(node:29408) UnhandledPromiseRejectionWarning: TypeError: Cannot read properties of undefined (reading 'catch')
      at AsyncTask.execute (D:\WorldX\worldxworkbench\Electron\node_modules\toad-scheduler\dist\lib\common\AsyncTask.js:16:13)
      at Cron.fn (D:\WorldX\worldxworkbench\Electron\node_modules\toad-scheduler\dist\lib\engines\cron\CronJob.js:29:27)
      at Cron._trigger (D:\WorldX\worldxworkbench\Electron\node_modules\toad-scheduler\node_modules\croner\dist\croner.min.cjs:1:21716)
      at Cron._checkTrigger (D:\WorldX\worldxworkbench\Electron\node_modules\toad-scheduler\node_modules\croner\dist\croner.min.cjs:1:22165)
      at Timeout._onTimeout (D:\WorldX\worldxworkbench\Electron\node_modules\toad-scheduler\node_modules\croner\dist\croner.min.cjs:1:21249)
      at listOnTimeout (node:internal/timers:569:17)
      at process.processTimers (node:internal/timers:512:7)
  (node:29408) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)

**Comment by LianXiaoxiang** [comment]
![image](https://github.com/kibertoad/toad-scheduler/assets/105619736/1ecc9671-9e5b-496c-a9b1-3ea13b413932)

**Comment by kibertoad** [comment]
You are not returning a promise from your AsyncTask

**Comment by LianXiaoxiang** [comment]
> You are not returning a promise from your AsyncTask

好吧 我换了一个库

**Comment by JaoodxD** [comment]
> You are not returning a promise from your AsyncTask

@kibertoad Just faced the very same issue. Would it be more convenient if `toad-scheduler` gently wrap a function result into a promise?
If it's a good idea I would like to contribute

**Comment by JaoodxD** [comment]
@kibertoad I encountered the issue again, but for a different reason.
The README recommends using promise chains over async/await with `AsyncTask`, which I followed. However, this conflicts with the common early return pattern. To use early returns, I either have to make the function async (violating the recommendation) or use `return Promise.resolve()`.
